### ISSUE TITLE
BufferOverflowException (possible encoding issue)

### ISSUE THREAD

**Issue by cergfix** [Happyr/fcgi4j#3]
Hello again :)

On some occasions there could be the following problem:

```
[Tue Apr 14 10:56:08 UTC 2015] - INFO: java.nio.BufferOverflowException
    at java.nio.HeapByteBuffer.put(HeapByteBuffer.java:189)
    at java.nio.ByteBuffer.put(ByteBuffer.java:859)
    at com.googlecode.fcgi4j.message.FCGIParams.getByteBuffers(FCGIParams.java:50)
    at com.googlecode.fcgi4j.FCGIConnection.flushParams(FCGIConnection.java:276)
    at com.googlecode.fcgi4j.FCGIConnection.readyWrite(FCGIConnection.java:379)
    at com.googlecode.fcgi4j.FCGIConnection.write(FCGIConnection.java:359)
```

It might be that it happens because of the following:

```
[Tue Apr 14 10:56:08 UTC 2015] - INFO: HTTP_X_GEOIP2_CITY=Łódź
```

So this may be an encoding issue. 

"com/googlecode/fcgi4j/message/FCGIParams.java" lines 55 and 66 could be returning incorrect numbers when special characters are present.

**Comment by Nyholm** [comment]
Thank you @cergfix for a very descriptive issue. It helped alot when I debugged this. 

I've provided a patch for this issue, please try it out to verify that it fix the problem for you.

**Comment by cergfix** [comment]
Fixed for me. Thanks!

**Comment by Nyholm** [comment]
I've bumped v0.2.3
