### ISSUE TITLE
php5-fpm: Connection reset by peer (read)

### ISSUE THREAD

**Issue by cergfix** [Happyr/fcgi4j#7]
The following issue occurs under some circumstances:

```
[Wed Jul 29 08:17:36 UTC 2015] - INFO: java.io.IOException: Connection reset by peer
    at sun.nio.ch.FileDispatcherImpl.read0(Native Method)
    at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39)
    at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
    at sun.nio.ch.IOUtil.read(IOUtil.java:192)
    at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380)
    at com.googlecode.fcgi4j.util.IoUtils.socketRread(IoUtils.java:29)
    at com.googlecode.fcgi4j.FCGIConnection.readHeader(FCGIConnection.java:257)
    at com.googlecode.fcgi4j.FCGIConnection.read(FCGIConnection.java:526)
```

Works OK under HHVM FastCGI, but throws an error when PHP5-FPM is used.

There is a bit of a difference in strace outputs:

PHP5-FPM:

```
[pid 23018] write(4, "\1\6\0\1\37\370\0\0Expires: Thu, 19 Nov 1981 08:52:00 GMT\r\nCache-Control: no-store, no-cache, must-revalidate, post-check=0, pre-check=0\r\nPragma: no-cache\r\nContent-type: text/html; charset=UTF-8\r\n\r\n<!DOCTYPE html PUBLIC...............
```

HHVM:

```
sendmsg(19, {msg_name(0)=NULL, msg_iov(20)=[{"\1\6\0\1\377\377\1\1", 8}, {"Content-Type: text/html\r\nExpires: Thu, 19 Nov 1981 08:52:00 GMT\r\nCache-Control: no-store, no-cache, must-revalidate, post-check=0, pre-check=0\r\nVary: Accept-Encoding\r\nPragma: no-cache\r\n\r\n<!DOCTYPE html PUBLIC...............
```

Also, enabling Xhprof in PHP5-FPM fixes the issue.

**Comment by cergfix** [comment]
The issue occurs when content data (POST) push is executed while the request method is set to GET.

Use a condition:

```
String requestMethod = "GET";
connection.setRequestMethod(requestMethod);
if(requestMethod.equalsIgnoreCase("POST")){
    connection.setContentLength(postData.length);
    connection.write(ByteBuffer.wrap(postData));
}
```

This issue affects PHP5-FPM only.

**Comment by Nyholm** [comment]
Okey. That is great that you have been troubleshooting. 
Can you send a PR?

**Comment by cergfix** [comment]
Working on it :)

**Comment by Nyholm** [comment]
You are awesome!

**Comment by cergfix** [comment]
Fixed in https://github.com/Happyr/fcgi4j/pull/8 as README update
